### ISSUE TITLE
Error al hacer el make

### ISSUE THREAD

**Issue by mdtrooper** [vterron/PyConES-2013#13]
Buenas.

No se mucho de latex, te pego el log:

```
/tmp/PyConES-2013 $ make
pdflatex -interaction=nonstopmode -halt-on-error python-cuarenta.tex
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./python-cuarenta.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 2 languages loaded.

! LaTeX Error: File `beamer.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.6 ^^M
       
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on python-cuarenta.log.
make: *** [pdf] Error 1
```

Saludos y gracias.

**Comment by vterron** [comment]
! LaTeX Error: File `beamer.cls' not found.

¿Tienes [Beamer](https://en.wikipedia.org/wiki/Beamer_(LaTeX)) instalado? Por ejemplo: `apt-get install latex-beamer`

**Comment by mdtrooper** [comment]
Exacto, si es que encima lo pone en el log que no esta, si llega a ser un lobo me come.

Lo siento por abrir un issue con esta tontería.

Saludos y gracias, muy buena la charleta, la ví en youtube.

**Comment by vterron** [comment]
No hay problema. Los comienzos con LaTeX no son precisamente fáciles :D
